# docker-compose up

version: '3.9'
services:


  ##########################################
  #                 NGINX
  ##########################################
  nginx:
    image: nginx:latest
    container_name: mynginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - common_network
    ports:
      - '8000:80'

  ##########################################
  #                 PHP
  ##########################################
  php-fpm:
    build:
      context: .
    ## Mettre à jour le fichier 'default.conf'
    # -> fastcgi_pass myphp_fpm:9000;
    container_name: myphp_fpm
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - common_network

networks:
  common_network:
    name: common_network
    driver: bridge

