# docker-compose up

version: '3.9'

services:

  ##########################################
  #                POSTGRES
  ##########################################
  postgres:
    image: postgres:14.1-alpine
    container_name: basic-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - php_default
    # shm_size: 128mb


  ##########################################
  #                 NGINX
  ##########################################
  nginx:
    image: nginx:latest
    container_name: mynginx
    volumes:
      - ./phppgadmin:/usr/share/nginx/phppgadmin
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php_default
    ## Accès de l'exterieur du 'container'
    # apt update && apt-get install -y postgresql-client
    # PGPASSWORD='postgres' psql -h basic-postgres -U postgres -d mydb
    ports:
      - '8000:80'

  ##########################################
  #                 PHP
  ##########################################
  php-fpm:
    build:
      context: .
    container_name: myphp_fpm
    volumes:
      - ./phppgadmin:/usr/share/nginx/phppgadmin
    networks:
      - php_default

networks:
  php_default:
    name: php_default
    driver: bridge

